name: Build
on:
  schedule:
    - cron:  '0 4 * * 2'
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/dellelce/postgresql-base

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mkit Postgresql 
        run: docker build -t $IMAGE . && docker push $IMAGE
